### ISSUE TITLE
How to pass siasky JWT?

### ISSUE THREAD

**Issue by murunwas** [michielpost/SiaSkynet#2]
How to pass JWT cookie to pin uploaded files to my siasky account?

**Comment by michielpost** [comment]
Currently not possible. Would it help if you could initialize the `SiaSkynetClient` with a custom HttpClient, so you can configure the cookie yourself on the client?

**Comment by murunwas** [comment]
yes please, it'll be easier to add additional headers

**Comment by michielpost** [comment]
Ok, I added a `SiaSkynetClient` constructor that takes a HttpClient, so you can customize the headers etc.
It's published on NuGet with version 3.4.1

**Comment by murunwas** [comment]
thank you @michielpost  let me test it, I'll post the feedback

**Comment by murunwas** [comment]
@michielpost   it's working 💯 , thank you

```csharp        
           var jwtcookie = new Cookie("skynet-jwt", AppSetting.JWT, "/", "siasky.net");
            HttpClientHandler handler = new HttpClientHandler();
            handler.CookieContainer.Add(jwtcookie);
            HttpClient client = new HttpClient(handler);
            var _client = new SiaSkynetClient(client, "https://siasky.net/");
```

**Comment by michielpost** [comment]
Great to hear!
If you have a nice app that uses this library, I can include it in the readme of this repository. Let me know! Very curious to know what people are using this for.

**Comment by 0x4ea** [comment]
how to see progress when upload a file?

**Comment by michielpost** [comment]
> how to see progress when upload a file?

Great question, I created a seperate issue for that: https://github.com/michielpost/SiaSkynet/issues/3
